### ISSUE TITLE
Implement Event Model, Database Implementation -- Monday 22nd

### ISSUE THREAD

**Issue by peter-n-andersson** [medmanager/backend#9]
-Create a database for the Event model
-Add events for the correct times in addNewMedication
-Remove old Events and add new Events in editMedication (for time-schedule change)

**Comment by davidburns573** [comment]
Attach scheduled cron object to DosageModel inside of the addNewMedication() function.

Rework functions in userModel to check dosageId's instead of testing the length of the eventSchema array
